<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>graphql</string>
		<string>GraphQL</string>
		<string>gql</string>
	</array>
	<key>foldingStartMarker</key>
	<string>{([</string>
	<key>foldingStopMarker</key>
	<string>})]</string>
	<key>name</key>
	<string>GraphQL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#enumSelections</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#definitions</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>a schema definintion</string>
			<key>match</key>
			<string>\b(schema)\b</string>
			<key>name</key>
			<string>meta.definition.schema</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>support.constant</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>a fragment definintion</string>
			<key>match</key>
			<string>(fragment)\s*([_A-Za-z][_0-9A-Za-z]*)\s*(on)\s*([_A-Za-z][_0-9A-Za-z]*)</string>
			<key>name</key>
			<string>meta.fragment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>an operation definition</string>
			<key>match</key>
			<string>(query|mutation)\s*([_A-Za-z][_0-9A-Za-z]*)</string>
			<key>name</key>
			<string>meta.operation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#arguments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#enumSelections</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#selections</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#nonNull</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>argument</key>
		<dict>
			<key>match</key>
			<string>[_A-Za-z][_0-9A-Za-z]*(?=\:)</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<key>arguments</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.round.query</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.round.query</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.arguments</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#argument</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nonNull</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
			</array>
		</dict>
		<key>boolean</key>
		<dict>
			<key>match</key>
			<string>true|false</string>
			<key>name</key>
			<string>constant.language.boolean</string>
		</dict>
		<key>builtInField</key>
		<dict>
			<key>match</key>
			<string>__schema|__typename|__type</string>
			<key>name</key>
			<string>keyword.other.query</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.query</string>
		</dict>
		<key>constants</key>
		<dict>
			<key>match</key>
			<string>\b(ID|Int|String|Float|Boolean)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<key>definitions</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>meta.type</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>meta.type</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(type|interface|input|scalar|union|enum)\s*([_A-Za-z][_0-9A-Za-z]*)(\s*(implements)\s*([_A-Za-z][_0-9A-Za-z]*)(\s*,\s*([_A-Za-z][_0-9A-Za-z]*))?)?</string>
			<key>name</key>
			<string>meta.definintion.type</string>
		</dict>
		<key>directive</key>
		<dict>
			<key>match</key>
			<string>@[a-z]+</string>
			<key>name</key>
			<string>storage.modifier</string>
		</dict>
		<key>enum</key>
		<dict>
			<key>match</key>
			<string>[_A-Za-z][_0-9A-Za-z]*</string>
			<key>name</key>
			<string>variable.parameter.enum</string>
		</dict>
		<key>enumSelections</key>
		<dict>
			<key>begin</key>
			<string>\b(enum)\s*[_A-Za-z][_0-9A-Za-z]*\s*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.selections.enum</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#definitions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enum</string>
				</dict>
			</array>
		</dict>
		<key>escapedChar</key>
		<dict>
			<key>match</key>
			<string>\\(?:u[\da-fA-f]{4}|.)</string>
			<key>name</key>
			<string>constant.character.escape.query</string>
		</dict>
		<key>fieldAlias</key>
		<dict>
			<key>match</key>
			<string>[_A-Za-z][_0-9A-Za-z]*(?=\:)</string>
			<key>name</key>
			<string>string.property.argument</string>
		</dict>
		<key>fieldWithArgs</key>
		<dict>
			<key>match</key>
			<string>[_A-Za-z][_0-9A-Za-z]*(?=\()</string>
			<key>name</key>
			<string>string.property</string>
		</dict>
		<key>fragmentSpread</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\.\.\.)\s*([_A-Za-z][_0-9A-Za-z]*)\s*(on)?</string>
		</dict>
		<key>inlineFragment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\.\.\.)\s*(on)\s*([_A-Za-z][_0-9A-Za-z]*)</string>
		</dict>
		<key>nonNull</key>
		<dict>
			<key>match</key>
			<string>\!</string>
			<key>name</key>
			<string>keyword.control.non-null</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>\d+\.?\d*[eE]?[\+\-]?\d*</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>\=|\|</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<key>selections</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.curly.query</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.brace.curly.query</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.selections</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#fieldAlias</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fieldWithArgs</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inlineFragment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fragmentSpread</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#directive</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arguments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#selections</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtInField</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nonNull</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escapedChar</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>\$[_A-Za-z][_0-9A-Za-z]*</string>
			<key>name</key>
			<string>constant.other.symbol</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.graphql</string>
	<key>uuid</key>
	<string>101a0bec-a04e-4f6b-8e55-9b8bdffa3cf8</string>
</dict>
</plist>
